# Generated by Django 4.2 on 2025-01-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='token',
            field=models.CharField(blank=True, max_length=36, verbose_name='token'),
        ),
    ]
