# Generated by Django 4.2 on 2025-01-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_alter_cartitems_is_purchased'),
        ('payments', '0002_alter_payment_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='items',
        ),
        migrations.AddField(
            model_name='payment',
            name='items',
            field=models.ManyToManyField(to='carts.cartitems', verbose_name='items'),
        ),
    ]
