# Generated by Django 4.2 on 2025-01-17 15:34

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=80, verbose_name='full name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone_number', models.BigIntegerField(validators=[utils.validators.PhoneNumberValidator()], verbose_name='phone number')),
                ('message', models.TextField(verbose_name='message')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='time')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': 'contact',
            },
        ),
    ]
