# Generated by Django 4.2 on 2025-01-18 05:16

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contactus_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='full_name',
            field=models.CharField(max_length=80, null=True, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(null=True, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone_number',
            field=models.BigIntegerField(null=True, validators=[utils.validators.PhoneNumberValidator()], verbose_name='phone number'),
        ),
    ]
