# Generated by Django 4.2 on 2025-03-04 20:01

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_contactus_email_alter_contactus_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='phone_number',
            field=models.CharField(max_length=12, null=True, validators=[utils.validators.PhoneNumberValidator()], verbose_name='phone number'),
        ),
    ]
