# Generated by Django 4.2 on 2025-01-04 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True, verbose_name='title')),
                ('is_enable', models.BooleanField(default=False, verbose_name='is enable')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='image')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.category', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=60, verbose_name='place')),
                ('event', models.CharField(max_length=100, verbose_name='title')),
                ('is_enable', models.BooleanField(default=False, verbose_name='is enable')),
                ('image', models.ImageField(upload_to='places/', verbose_name='image')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('address', models.TextField(verbose_name='address')),
                ('area', models.CharField(blank=True, max_length=60, null=True, verbose_name='area')),
                ('city', models.CharField(max_length=80, verbose_name='city')),
                ('price', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='price')),
                ('capacity', models.PositiveIntegerField(verbose_name='capacity')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('event_date', models.DateTimeField(verbose_name='event date')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Places',
                'db_table': 'places',
            },
        ),
    ]
