# Generated by Django 4.2 on 2025-01-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_place_event_time_alter_place_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='event_date',
            field=models.DateField(max_length=50, verbose_name='event date'),
        ),
    ]
