# Generated by Django 4.2 on 2025-01-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_place_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='like',
            field=models.IntegerField(default=0, verbose_name='like'),
        ),
    ]
