# Generated by Django 4.2 on 2025-01-18 16:37

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_superuser_alter_user_last_seen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.BigIntegerField(blank=True, error_messages={'unique': 'A user with that phone number already exists.'}, help_text='با 98 شروع کن', null=True, validators=[utils.validators.PhoneNumberValidator()], verbose_name='phone number'),
        ),
    ]
