# Generated by Django 4.2 on 2025-01-21 13:51

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, error_messages={'unique': 'کاربری با آن شماره تلفن از قبل وجود دارد.'}, max_length=12, null=True, validators=[utils.validators.PhoneNumberValidator()], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'کاربری با این نام کاربری از قبل وجود دارد.'}, help_text='30 کاراکتر یا کمتر که با یک حرف شروع می شود. فقط حروف، اعداد و خط زیر خط.', max_length=30, unique=True, validators=[utils.validators.UsernameValidator()], verbose_name='username'),
        ),
    ]
