# Generated by Django 4.2 on 2025-02-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0002_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Paid'), (30, 'User Canceled')], default=30, verbose_name='status'),
        ),
    ]
