# Generated by Django 4.2 on 2025-01-29 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0007_alter_place_event_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User_info',
                'verbose_name_plural': 'User_infos',
                'db_table': 'user_info',
            },
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='quantity')),
                ('is_purchased', models.BooleanField(default=False, verbose_name='is purchased')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place', verbose_name='place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='CartItemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='quantity')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='price')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='event date')),
                ('city', models.CharField(blank=True, max_length=80, null=True, verbose_name='city')),
                ('category', models.CharField(max_length=80, null=True, verbose_name='category')),
                ('place_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='place')),
                ('event', models.CharField(blank=True, max_length=100, null=True, verbose_name='title')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cart_info',
                'verbose_name_plural': 'Cart_infos',
                'db_table': 'cart_info',
            },
        ),
    ]
