# Generated by Django 4.2 on 2025-01-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_cartitems_options_alter_cartitems_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date added'),
        ),
    ]
