# Generated by Django 4.2 on 2025-01-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_alter_cartitems_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='is_purchased',
            field=models.BooleanField(default=False, verbose_name='is_purchased'),
        ),
    ]
