# Generated by Django 4.2 on 2025-01-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_cartitems_is_purchased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='is_purchased',
            field=models.BooleanField(default=False, verbose_name='is purchased'),
        ),
    ]
