# Generated by Django 4.2 on 2025-01-19 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_alter_cartitems_date_added'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.cartitems', verbose_name='items'),
        ),
    ]
