# Generated by Django 4.2 on 2025-01-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_alter_cartitems_is_purchased'),
        ('subscriptions', '0002_alter_subscription_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='items',
        ),
        migrations.AddField(
            model_name='subscription',
            name='items',
            field=models.ManyToManyField(to='carts.cartitems'),
        ),
    ]
